[package]
name = "redis-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0.204", features = ["derive"] }

[dependencies.redis]
git = "https://github.com/redis-rs/redis-rs.git"

